"""
azure_migrator.py — Upload keyframes & embeddings to Azure Blob Storage
========================================================================
CLI script designed to run on Google Colab after artifacts have been
generated by the LMSKE + embedding pipeline.

Usage (Colab):
    # 1. Set your connection string as an environment variable
    import os
    os.environ["AZURE_STORAGE_CONNECTION_STRING"] = "<your-connection-string>"

    # 2. Run the migration
    !python azure_migrator.py \
        --frames_dir  "/content/drive/MyDrive/output" \
        --embeddings_dir "/content/drive/MyDrive/embeddings" \
        --workers 10
"""

from __future__ import annotations

# ── 0. Auto-install (Colab-friendly) ──────────────────────────────────────────
import subprocess
import sys


def _pip(*pkgs: str) -> None:
    subprocess.check_call(
        [sys.executable, "-m", "pip", "install", "-q", *pkgs]
    )


try:
    from azure.storage.blob import BlobServiceClient  # noqa: F401
except ImportError:
    _pip("azure-storage-blob")

# ── 1. Imports ────────────────────────────────────────────────────────────────
import argparse
import logging
import os
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import NamedTuple

from azure.storage.blob import BlobServiceClient, ContentSettings
from azure.core.exceptions import ResourceExistsError, HttpResponseError

# ── 2. Logging setup ─────────────────────────────────────────────────────────
LOG_FORMAT = "[%(asctime)s] %(levelname)-8s %(message)s"
DATE_FORMAT = "%Y-%m-%d %H:%M:%S"

# Console handler
console_handler = logging.StreamHandler(sys.stdout)
console_handler.setLevel(logging.INFO)
console_handler.setFormatter(logging.Formatter(LOG_FORMAT, datefmt=DATE_FORMAT))

# File handler — errors only
file_handler = logging.FileHandler("migration_errors.log", encoding="utf-8")
file_handler.setLevel(logging.ERROR)
file_handler.setFormatter(logging.Formatter(LOG_FORMAT, datefmt=DATE_FORMAT))

logger = logging.getLogger("azure_migrator")
logger.setLevel(logging.DEBUG)
logger.addHandler(console_handler)
logger.addHandler(file_handler)


# ── 3. Data structures ───────────────────────────────────────────────────────
class UploadTask(NamedTuple):
    """Represents a single file that needs to be uploaded."""
    local_path: Path
    container: str
    blob_path: str  # e.g. "video_id/filename.jpg"


# ── 4. CLI ────────────────────────────────────────────────────────────────────
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Upload keyframe images and embedding files from local/Google-Drive "
            "directories to Azure Blob Storage."
        ),
    )
    parser.add_argument(
        "--frames_dir",
        type=Path,
        required=True,
        help=(
            "Root directory containing keyframe images. "
            "Expected structure: <frames_dir>/<video_id>/*.jpg"
        ),
    )
    parser.add_argument(
        "--embeddings_dir",
        type=Path,
        required=True,
        help=(
            "Root directory containing embedding files (.npy, _frames.json). "
            "Expected structure: <embeddings_dir>/<video_id>.npy"
        ),
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=10,
        help="Number of concurrent upload threads (default: 10).",
    )
    return parser.parse_args()


# ── 5. Discovery ─────────────────────────────────────────────────────────────
def discover_keyframes(frames_dir: Path) -> list[UploadTask]:
    """
    Scan <frames_dir> for .jpg files.
    Expected layout:
        frames_dir/
        ├── video_id_A/
        │   ├── video_id_A_00001.jpg
        │   └── video_id_A_00002.jpg
        └── video_id_B/
            └── video_id_B_00001.jpg

    Each file is routed to Azure container "keyframes" at path:
        {video_id}/{filename.jpg}
    """
    tasks: list[UploadTask] = []
    if not frames_dir.is_dir():
        logger.warning(f"Frames directory not found, skipping: {frames_dir}")
        return tasks

    for subdir in sorted(frames_dir.iterdir()):
        if not subdir.is_dir():
            continue
        video_id = subdir.name
        for img in sorted(subdir.glob("*.jpg")):
            blob_path = f"{video_id}/{img.name}"
            tasks.append(UploadTask(local_path=img, container="keyframes", blob_path=blob_path))

    logger.info(f"Discovered {len(tasks)} keyframe file(s) in {frames_dir}")
    return tasks


def discover_embeddings(embeddings_dir: Path) -> list[UploadTask]:
    """
    Scan <embeddings_dir> for .npy and _frames.json files.
    Expected layout:
        embeddings_dir/
        ├── video_id_A.npy
        ├── video_id_A_frames.json
        ├── video_id_B.npy
        └── video_id_B_frames.json

    video_id is derived from the filename (stem before the first dot / suffix).
    Each file is routed to Azure container "embeddings" at path:
        {video_id}/{filename}
    """
    tasks: list[UploadTask] = []
    if not embeddings_dir.is_dir():
        logger.warning(f"Embeddings directory not found, skipping: {embeddings_dir}")
        return tasks

    valid_suffixes = {".npy", ".json"}
    for fpath in sorted(embeddings_dir.iterdir()):
        if not fpath.is_file():
            continue
        if fpath.suffix.lower() not in valid_suffixes:
            continue

        # Derive video_id:  "video_id_A.npy"       -> "video_id_A"
        #                    "video_id_A_frames.json" -> "video_id_A"
        stem = fpath.stem
        if stem.endswith("_frames"):
            video_id = stem[: -len("_frames")]
        else:
            video_id = stem

        blob_path = f"{video_id}/{fpath.name}"
        tasks.append(UploadTask(local_path=fpath, container="embeddings", blob_path=blob_path))

    logger.info(f"Discovered {len(tasks)} embedding file(s) in {embeddings_dir}")
    return tasks


# ── 6. Upload logic ──────────────────────────────────────────────────────────
def blob_exists(blob_client) -> bool:
    """Return True if the blob already exists on Azure."""
    try:
        blob_client.get_blob_properties()
        return True
    except HttpResponseError:
        return False


def upload_single(
    task: UploadTask,
    blob_service_client: BlobServiceClient,
) -> tuple[str, bool, str]:
    """
    Upload a single file to Azure Blob Storage.

    Returns:
        (blob_path, success: bool, message: str)
    """
    try:
        blob_client = blob_service_client.get_blob_client(
            container=task.container,
            blob=task.blob_path,
        )

        # ── Idempotency: skip if already uploaded ────────────────────────
        if blob_exists(blob_client):
            return (task.blob_path, True, "skipped (already exists)")

        # ── Determine content type ───────────────────────────────────────
        suffix = task.local_path.suffix.lower()
        content_type_map = {
            ".jpg": "image/jpeg",
            ".jpeg": "image/jpeg",
            ".png": "image/png",
            ".npy": "application/octet-stream",
            ".json": "application/json",
        }
        content_type = content_type_map.get(suffix, "application/octet-stream")

        # ── Upload ───────────────────────────────────────────────────────
        with open(task.local_path, "rb") as data:
            blob_client.upload_blob(
                data,
                overwrite=False,
                content_settings=ContentSettings(content_type=content_type),
            )

        size_mb = task.local_path.stat().st_size / (1024 * 1024)
        return (task.blob_path, True, f"uploaded ({size_mb:.2f} MB)")

    except ResourceExistsError:
        return (task.blob_path, True, "skipped (already exists)")

    except Exception as exc:
        return (task.blob_path, False, f"FAILED: {exc}")


# ── 7. Main ───────────────────────────────────────────────────────────────────
def main() -> None:
    args = parse_args()

    # ── Validate connection string ───────────────────────────────────────
    conn_str = os.environ.get("AZURE_STORAGE_CONNECTION_STRING")
    if not conn_str:
        logger.error(
            "Environment variable AZURE_STORAGE_CONNECTION_STRING is not set. "
            "Please set it before running this script.\n"
            '  export AZURE_STORAGE_CONNECTION_STRING="DefaultEndpointsProtocol=..."'
        )
        sys.exit(1)

    blob_service_client = BlobServiceClient.from_connection_string(conn_str)

    # ── Ensure containers exist ──────────────────────────────────────────
    for container_name in ("keyframes", "embeddings"):
        try:
            blob_service_client.create_container(container_name)
            logger.info(f"Created container: {container_name}")
        except ResourceExistsError:
            logger.info(f"Container already exists: {container_name}")
        except Exception as exc:
            logger.error(f"Failed to create container '{container_name}': {exc}")
            sys.exit(1)

    # ── Discover files ───────────────────────────────────────────────────
    logger.info("=" * 60)
    logger.info("Azure Blob Storage Migration")
    logger.info("=" * 60)
    logger.info(f"Frames dir:     {args.frames_dir}")
    logger.info(f"Embeddings dir: {args.embeddings_dir}")
    logger.info(f"Workers:        {args.workers}")
    logger.info("")

    tasks: list[UploadTask] = []
    tasks.extend(discover_keyframes(args.frames_dir))
    tasks.extend(discover_embeddings(args.embeddings_dir))

    if not tasks:
        logger.warning("No files discovered. Nothing to upload.")
        return

    # ── Upload with ThreadPoolExecutor ───────────────────────────────────
    logger.info(f"Starting upload of {len(tasks)} file(s) with {args.workers} worker(s)...")
    start_time = time.time()

    success_count = 0
    skip_count = 0
    fail_count = 0

    with ThreadPoolExecutor(max_workers=args.workers) as executor:
        future_to_task = {
            executor.submit(upload_single, task, blob_service_client): task
            for task in tasks
        }

        for i, future in enumerate(as_completed(future_to_task), 1):
            task = future_to_task[future]
            try:
                blob_path, ok, message = future.result()
            except Exception as exc:
                blob_path = task.blob_path
                ok = False
                message = f"FAILED (future exception): {exc}"

            if ok:
                if "skipped" in message:
                    skip_count += 1
                    logger.debug(f"[{i}/{len(tasks)}] {task.container}/{blob_path} — {message}")
                else:
                    success_count += 1
                    logger.info(f"[{i}/{len(tasks)}] {task.container}/{blob_path} — {message}")
            else:
                fail_count += 1
                logger.error(f"[{i}/{len(tasks)}] {task.container}/{blob_path} — {message}")

    elapsed = time.time() - start_time

    # ── Summary ──────────────────────────────────────────────────────────
    logger.info("")
    logger.info("=" * 60)
    logger.info("Migration Complete!")
    logger.info("=" * 60)
    logger.info(f"Total files:  {len(tasks)}")
    logger.info(f"Uploaded:     {success_count}")
    logger.info(f"Skipped:      {skip_count}")
    logger.info(f"Failed:       {fail_count}")
    logger.info(f"Elapsed time: {elapsed:.1f}s")

    if fail_count > 0:
        logger.warning(
            f"{fail_count} file(s) failed. Check migration_errors.log for details."
        )


if __name__ == "__main__":
    main()
